### ISSUE TITLE
Cannot run in real Unitree A1

### ISSUE THREAD

**Issue by anahrendra** [lauramsmith/fine-tuning-locomotion#5]
Hi! Thank you for sharing your work.

However, I found some trouble when implementing the MPC to a real A1 robot. It works fine in the first one second, and starts to lose its balance an acted weirdly afterwards.

May I know your computing device to run the MPC?

Thanks in advance!

**Comment by mashli** [comment]
> Hi! Thank you for sharing your work.
> 
> However, I found some trouble when implementing the MPC to a real A1 robot. It works fine in the first one second, and starts to lose its balance an acted weirdly afterwards.
> 
> May I know your computing device to run the MPC?
> 
> Thanks in advance!
Dear anahrendra
I encountered the same problem. 
Have you fixed this problem? 
Thank you!

**Comment by anahrendra** [comment]
I solved it by using an NUC to run the code. Previously I used the built-in Jetson. Probably its not strong enough to run the MPC in real time

**Comment by mashli** [comment]
> I solved it by using an NUC to run the code. Previously I used the built-in Jetson. Probably its not strong enough to run the MPC in real time
Thank you ,  anahrendra.
